services:
  device_management:
    build: ./device_management
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    container_name: device_management
    env_file:
      - ./device_management.env

  telemetry:
    build: ./telemetry
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8082:8082"
    container_name: telemetry
    env_file:
      - ./telemetry.env

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=smart_home
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "smart_home" ]
      interval: 30s
      timeout: 60s
      retries: 5

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/database:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=username
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=smart_home
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "localhost:8123/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3


